name: learn-github-actions
on:
  pull_request:
    types: [closed]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
      - run: echo "GITHUB_EVENT_PATH $GITHUB_EVENT_PATH"
      - run: cat "$GITHUB_EVENT_PATH"
      - run: echo "GITHUB_SHA        $GITHUB_SHA"
      - run: echo "GITHUB_REF        $GITHUB_REF"
      - run: echo "GITHUB_HEAD_REF   $GITHUB_HEAD_REF"
      - run: echo "GITHUB_BASE_REF   $GITHUB_BASE_REF"
      - run: <$GITHUB_EVENT_PATH jq --raw '.pull_request.head | (.ref, .merged)'
